version: '2'

services:
  hadoop-namenode:
    image: uhopper/hadoop-namenode:latest
    hostname: hadoop-namenode
    ports:
      - "8020:8020"
      - "50070:50070"
    environment:
      CLUSTER_NAME: hdfs-network
      HDFS_CONF_dfs_replication: 1

  hadoop-datanode:
    image: uhopper/hadoop-datanode:latest
    environment:
      CORE_CONF_fs_defaultFS: hdfs://hadoop-namenode:8020
      CLUSTER_NAME: hdfs-network
      HDFS_CONF_dfs_replication: 1


  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - "2182:2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  data-generator:
    build: ./data-generator
    depends_on:
    - kafka
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC: queueing.sensors
      DATA_PER_SECOND: 1

  data-consumer:
    build: ./data-consumer
    environment:
      KAFKA_BROKER_URL: kafka:9092
      HDFS_URL: hadoop-namenode:8020
      TOPIC: queueing.sensors    
      BATCH_SIZE: 100

networks:
  default:
    external:
      name: hdfs-network
