version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - "2182:2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  data-generator:
    build: ./data-generator
    depends_on:
    - kafka
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC: queueing.sensors
      DATA_PER_SECOND: 1

  data-consumer:
    build: ./data-consumer
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC: queueing.sensors

  data-digestion:
    build: ./data-digestion
    hostname: flume.sensors.com
    container_name: flume.sensors.com
    restart: always
    environment:
      AGENT: agent
    volumes:
      - ${PWD}/data-digestion/kafkaFlume.properties:/apache-flume/conf/flume-conf.properties

networks:
  default:
    external:
      name: kafka-network
